DROP DATABASE LAB3;
CREATE DATABASE LAB3;
USE LAB3;

CREATE TABLE IF NOT EXISTS STUDENT (
	SID INT(11) PRIMARY KEY AUTO_INCREMENT,
	SNAME VARCHAR(20) NOT NULL,
	AGE INT(10) NOT NULL
	);

CREATE TABLE IF NOT EXISTS COURSE (
	CID INT(11) PRIMARY KEY AUTO_INCREMENT,
	CNAME VARCHAR(20) NOT NULL,
	CREADIT INT(10) NOT NULL
	);

CREATE TABLE IF NOT EXISTS SC (
	SID INT(11) NOT NULL,
	CID INT(11) NOT NULL,
	SCORE INT(10) NOT NULL,
	FOREIGN KEY FO_S (SID) REFERENCES STUDENT(SID) ON DELETE CASCADE ON UPDATE CASCADE,	
	FOREIGN KEY FO_C (CID) REFERENCES COURSE(CID) ON DELETE CASCADE ON UPDATE CASCADE
	);

INSERT INTO STUDENT VALUES
	(NULL, 'AAA', 17),
	(NULL, 'BBB', 18),
	(NULL, 'CCC', 19);

INSERT INTO COURSE VALUES
	(NULL, 'MATH', 17),
	(NULL, 'PHYSICS', 18);

INSERT INTO SC VALUES
	(1, 1, 100),
	(1, 2, 99),
	(2, 1, 98),
	(2, 2, 97),
	(3, 1, 96),
	(3, 2, 95);

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SC;

/*
INSERT INTO SC VALUES
	(4, 1, 88);
*/

DELIMITER $$
CREATE PROCEDURE CHANGE_SID(IN OLD_SID INT, IN NEW_SID INT)
BEGIN
	UPDATE STUDENT SET SID = NEW_SID WHERE SID = OLD_SID;
END;
$$
DELIMITER ;

CALL CHANGE_SID(3, 9);


SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SC;