DROP DATABASE LAB3;
CREATE DATABASE LAB3;
USE LAB3;

CREATE TABLE IF NOT EXISTS DEPT (
	DID INT(11) PRIMARY KEY AUTO_INCREMENT,
	DNAME VARCHAR(20) NOT NULL,
	S_COUNT INT(11) NOT NULL
	);

CREATE TABLE IF NOT EXISTS STU (
	SID INT(11) PRIMARY KEY AUTO_INCREMENT,
	SNAME VARCHAR(20) NOT NULL,
	AGE INT (10) NOT NULL,
	DID INT (11) NOT NULL,
	FOREIGN KEY FO_D (DID) REFERENCES DEPT(DID) ON DELETE CASCADE ON UPDATE CASCADE	
	);

DROP TRIGGER IF EXISTS INSERT_S_COUNT;

DELIMITER $$
CREATE TRIGGER INSERT_S_COUNT AFTER INSERT ON STU FOR EACH ROW
BEGIN
	UPDATE DEPT SET S_COUNT = S_COUNT + 1 WHERE NEW.DID = DID;
END
$$
DELIMITER ;

DROP TRIGGER IF EXISTS UPDATE_S_COUNT;

DELIMITER $$
CREATE TRIGGER UPDATE_S_COUNT AFTER UPDATE ON STU FOR EACH ROW
BEGIN
	UPDATE DEPT SET S_COUNT = S_COUNT + 1 WHERE NEW.DID = DID;
	UPDATE DEPT SET S_COUNT = S_COUNT - 1 WHERE OLD.DID = DID;
END
$$
DELIMITER ;

INSERT INTO DEPT VALUES
	(NULL, 'MATH', 0),
	(NULL, 'CHINESE', 0),
	(NULL, 'PHYSICS', 0);

INSERT INTO STU VALUES
	(NULL, 'STEVE', '18', 2),
	(NULL, 'DAVE', '18', 2);

SELECT * FROM STU;
SELECT * FROM DEPT;

UPDATE STU SET DID = 1 WHERE SID = 2;

SELECT * FROM STU;
SELECT * FROM DEPT;
